#!/usr/bin/env python3
"""Render a measured proposal into the linter's own config format.

This exists because the translation is where the criterion gets lost. Adopting a proposal by hand
against `theo-cloud` took four attempts, and every failure was a translation detail rather than a
wrong rule:

1. a component key written without its `:` — 32 schema errors, reported as `ExecutionWarnings`,
   a field nothing reads. `ArchWarningsDeps` said 0. Green, having validated nothing.
2. `in: internal/auth` matches that directory and not its subpackages — 24 packages left
   ungoverned.
3. a unit importing its own subpackages counts as a self-dependency, which go-arch-lint forbids
   unless the unit lists itself — 63 violations that were not boundary crossings at all.
4. the allow-list was derived from production imports while the linter scanned tests too — 49
   violations from `_test.go` files alone.

The tempting fix for each was to widen the rule. That is how a gate becomes decoration, so the
fixes here go the other way: the config is generated to enforce *exactly* the set that was
measured, and anything outside that set is declared out of scope rather than quietly allowed.
"""
from __future__ import annotations

import json
import sys

#: Directories whose contents are somebody else's code. `theo-cloud` vendors a Go file inside its
#: dashboard's node_modules, and without this it lands in the report as an ungoverned package
#: forever — noise that trains readers to ignore the coverage number.
_EXCLUDE_DIRS = ("**/node_modules", "**/vendor", "**/testdata")


def _component(unit: str) -> str:
    """A YAML-safe component name. `.` is the module-root package, named `root` for readability."""
    if unit == ".":
        return "root"
    return unit.replace("/", "_").replace("-", "_").replace(".", "_")


def go_arch_lint(proposal: dict, *, measured_on: str) -> str:
    """Render a `.go-arch-lint.yml` that enforces exactly the measured allow-list."""
    allowed = proposal.get("allow_list") or {}
    if not allowed:
        raise ValueError("proposal carries no allow_list — nothing to enforce")

    lines = [
        "version: 3",
        "",
        f"# Generated by /arch-check from the import graph measured on {measured_on}.",
        f"# {len(allowed)} units, {proposal.get('total_edges', 0)} edges, "
        f"{len(proposal.get('cycles') or [])} cycles.",
        "#",
        "# Every rule below was true BEFORE it was written: this file freezes the state the repo",
        "# already had, it does not announce debt. A rule that fails on its first run was adopted",
        "# against that criterion and should be a backlog item instead.",
        "",
        "# Somebody else's code, vendored into the tree.",
        "exclude:",
        # Quoted: a scalar starting with `*` is an ALIAS in YAML, so an unquoted
        # `**/node_modules` parses to null and the exclusion silently does nothing.
        # Measured: three `Invalid type. Expected: string, given: null` warnings.
        *[f'  - "{pattern}"' for pattern in _EXCLUDE_DIRS],
        "",
        "# The enforced set is the MEASURED set. The allow-list was derived from production",
        "# imports, so tests are out of scope here rather than silently widening it — see",
        "# `test_only_edges` in the proposal for the crossings this leaves ungoverned.",
        "excludeFiles:",
        '  - "_test\\\\.go$"',
        "",
        "components:",
    ]
    width = max((len(_component(u)) for u in allowed), default=0) + 1
    for unit in allowed:
        # Both forms: the directory itself AND its subtree. `in: x` alone leaves every subpackage
        # matched by no component, which reads as coverage while covering nothing.
        # `.` covers the module root's own files and nothing below it, so it takes no `/**`
        # sibling — adding one would make the root component swallow every package in the module.
        selector = "." if unit == "." else f"[{unit}, {unit}/**]"
        lines.append(f"  {_component(unit) + ':':<{width}} {{ in: {selector} }}")

    lines += ["", "deps:"]
    for unit, targets in allowed.items():
        # The unit lists ITSELF: an import between its own subpackages is internal cohesion, not a
        # boundary crossing, and forbidding it would make the config red for the wrong reason.
        may = [_component(unit)] + [_component(target) for target in targets]
        lines.append(f"  {_component(unit)}:")
        lines.append(f"    mayDependOn: [{', '.join(may)}]")
        lines.append("    anyVendorDeps: true")
    return "\n".join(lines) + "\n"


def split_by_module(proposal: dict) -> dict[str, dict]:
    """One sub-proposal per module directory, for repos go-arch-lint cannot read whole.

    go-arch-lint resolves a project from its `go.mod`: pointed at a `go.work` root it exits with
    *"not found project 'go.mod'"*. A multi-module repo therefore needs one config per module,
    not one per repo — and `theo` has eight. Units are already namespaced by module directory, so
    the split is a regrouping rather than a re-measurement.
    """
    modules = proposal.get("modules") or []
    if not modules:
        return {"": proposal}

    out: dict[str, dict] = {}
    for module in modules:
        prefix = f"{module}/"
        allowed = {
            unit[len(prefix) :]: [t[len(prefix) :] for t in targets if t.startswith(prefix)]
            for unit, targets in (proposal.get("allow_list") or {}).items()
            if unit.startswith(prefix)
        }
        if allowed:
            out[module] = {**proposal, "allow_list": allowed}
    return out


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) < 1:
        print("usage: emit_config.py <proposal.json> [--measured-on YYYY-MM-DD]", file=sys.stderr)
        return 2
    measured_on = args[args.index("--measured-on") + 1] if "--measured-on" in args else "an unrecorded date"

    with open(args[0], encoding="utf-8") as handle:
        proposal = json.load(handle)

    if proposal.get("status") != "proposed":
        print(
            f"refusing to emit: proposal status is {proposal.get('status')!r}. "
            f"{proposal.get('reason', '')}",
            file=sys.stderr,
        )
        return 1
    if proposal.get("language") != "go":
        print(
            f"no renderer for {proposal.get('language')!r} yet — go only. TypeScript boundaries "
            "go in `.dependency-cruiser.cjs`, whose rules are hand-written prose plus a regex, "
            "and generating that badly is worse than writing five rules by hand.",
            file=sys.stderr,
        )
        return 1

    per_module = split_by_module(proposal)
    if len(per_module) == 1 and "" in per_module:
        print(go_arch_lint(proposal, measured_on=measured_on), end="")
        return 0

    # A workspace gets one file per module, each written where go-arch-lint will look for it.
    out_dir = args[args.index("--out") + 1] if "--out" in args else None
    if out_dir is None:
        print(
            f"this repo has {len(per_module)} modules and go-arch-lint reads one `go.mod` at a "
            "time, so it needs one config per module. Re-run with `--out <dir>` to write them.",
            file=sys.stderr,
        )
        for module in per_module:
            print(f"  {module}/.go-arch-lint.yml", file=sys.stderr)
        return 1

    from pathlib import Path as _Path  # noqa: PLC0415

    for module, sub in per_module.items():
        target = _Path(out_dir) / module / ".go-arch-lint.yml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(go_arch_lint(sub, measured_on=measured_on), encoding="utf-8")
        print(f"wrote {target} ({len(sub['allow_list'])} units)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
