#!/usr/bin/env python3
"""Generate — and verify — the index that opens a BACKLOG.md.

## Why this is generated rather than written

A registry answers "what is pending?" only if you can see the answer without reading it all.
Measured across the four registries in this ecosystem: 592 items in blocks, and **zero** index
rows. The answer existed only as a `grep` over `status:`.

The obvious fix is a table at the top. The obvious fix is also the one that rots: 592 items, and
the index is wrong the moment one of them changes status — silently, because nothing compares the
two. An index that disagrees with the items is worse than none, since a reader who trusts it
reports absence where evidence exists. That is the same failure `rules/knowledge-base-location.md`
records for a split knowledge-base, and the same one the D5 meta-gate exists to catch.

So the index is derived from the item blocks, and `check_backlog_structure.py` fails when the
file's index does not match the one this module would generate. Hand-editing it is not forbidden;
it is *detected*.

## The three buckets

`cycle-backlog.md` declares five statuses. A reader asking "what is pending?" wants three:

    open        raw, triaged      registered and measured, but nothing is being built
    in-flight   planned           a plan exists; work is under way
    closed      shipped, killed   the chain ended — killed is a SUCCESSFUL ending

`triaged` sits in `open` on purpose. Measurement has run, but no plan exists, so nothing is in
flight; calling it in-flight would make the in-flight count answer a different question than the
one people ask of it ("what is someone building right now?").
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

# One definition of "an item", shared with the structural gate. A second parser here would drift
# from it in silence, and the two would disagree about what the registry contains — which is the
# precise defect this index exists to make visible.
from check_backlog_structure import BLOCK_RE, Item, _parse_items  # noqa: E402

#: The generated block is delimited so it can be replaced without touching anything a human wrote.
START = "<!-- BACKLOG-INDEX:START — generated by backlog_index.py; edits here are overwritten -->"
END = "<!-- BACKLOG-INDEX:END -->"

#: status -> bucket. Statuses absent here are reported rather than silently bucketed: an unknown
#: status means the contract changed and this file did not.
BUCKETS: dict[str, str] = {
    "raw": "open",
    "triaged": "open",
    "planned": "in-flight",
    "shipped": "closed",
    "killed": "closed",
}
BUCKET_ORDER = ("open", "in-flight", "closed")
BUCKET_LABEL = {
    "open": "Open",
    "in-flight": "In flight",
    "closed": "Closed",
}


def anchor(heading_text: str) -> str:
    """The fragment GitHub derives from a heading, so the index links resolve in the rendered file.

    GitHub's rule: lowercase, drop every character that is not a letter, digit, space, hyphen or
    underscore, then turn spaces into hyphens. Consecutive spaces become consecutive hyphens, and
    that is not a bug to smooth over — `B-018 — Title   [x]` really does render an anchor with the
    doubled and tripled hyphens, and "tidying" them here would produce links that 404.
    """
    text = heading_text.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    return text.replace(" ", "-")


def heading_of(content: str, item: Item) -> str:
    """The item's heading line, verbatim — the anchor has to be derived from what is on the page."""
    for match in BLOCK_RE.finditer(content):
        if match.group(1) == item.item_id:
            return match.group(0).lstrip("#").strip()
    return f"{item.item_id} — {item.title}"


def bucket_of(item: Item) -> str | None:
    return BUCKETS.get(item.fields.get("status", ""))


def render_index(content: str, items: list[Item]) -> str:
    """The index block, markers included."""
    rows: dict[str, list[str]] = {b: [] for b in BUCKET_ORDER}
    unknown: list[Item] = []
    for item in items:
        bucket = bucket_of(item)
        if bucket is None:
            unknown.append(item)
            continue
        frag = anchor(heading_of(content, item))
        status = item.fields.get("status", "?")
        severity = item.fields.get("severity", "—")
        rows[bucket].append(
            f"| [`{item.item_id}`](#{frag}) | {item.title} | `{status}` | {severity} |"
        )

    total = sum(len(rows[b]) for b in BUCKET_ORDER) + len(unknown)
    counts = " · ".join(f"**{BUCKET_LABEL[b]}** {len(rows[b])}" for b in BUCKET_ORDER)

    out = [START, "", "## Index", "", f"{total} items — {counts}", ""]
    if unknown:
        ids = ", ".join(i.item_id for i in unknown)
        out += [
            f"> **{len(unknown)} item(s) carry a status this index does not know**: {ids}. "
            "They are counted in the total and listed nowhere else — a status outside the "
            "declared set means the contract moved and this table did not follow it.",
            "",
        ]
    for b in BUCKET_ORDER:
        out += [f"### {BUCKET_LABEL[b]} ({len(rows[b])})", ""]
        if rows[b]:
            out += ["| Item | Title | Status | Severity |", "|---|---|---|---|", *rows[b], ""]
        else:
            out += ["_None._", ""]
    out.append(END)
    return "\n".join(out)


def apply_index(content: str, index_block: str) -> str:
    """Replace the existing block, or insert one immediately before the item registry.

    Inserting before `## Items` rather than at the top of the file is deliberate: the prose above
    it explains how an item gets here and how routing works, and a reader needs that before a
    table of 592 rows is useful.
    """
    if START in content and END in content:
        head, _, rest = content.partition(START)
        _, _, tail = rest.partition(END)
        return head + index_block + tail

    # `Items`, `Itens`, `Itens abertos` — all three are on disk in this ecosystem right now, so
    # anchoring on one spelling would silently append the index to the end of the file for the
    # other two, which is the one place nobody reads.
    marker = re.search(r"^##\s+Ite[mn]s\b.*$", content, re.MULTILINE)
    if marker:
        cut = marker.start()
        return content[:cut] + index_block + "\n\n" + content[cut:]
    return content.rstrip() + "\n\n" + index_block + "\n"


def index_is_current(content: str) -> tuple[bool, str]:
    """`(matches?, expected_block)` — the comparison the structural gate reports on."""
    expected = render_index(content, _parse_items(content))
    if START not in content or END not in content:
        return False, expected
    present = content[content.index(START) : content.index(END) + len(END)]
    return present == expected, expected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or verify a BACKLOG.md index.")
    parser.add_argument("backlog", type=Path, nargs="?", default=Path("BACKLOG.md"))
    parser.add_argument("--write", action="store_true", help="rewrite the file in place")
    parser.add_argument("--check", action="store_true", help="exit 1 when the index is stale")
    args = parser.parse_args(argv)

    if not args.backlog.exists():
        print(f"BACKLOG.md not found at {args.backlog}", file=sys.stderr)
        return 2

    content = args.backlog.read_text(encoding="utf-8-sig")
    current, expected = index_is_current(content)

    if args.check:
        print(f"{args.backlog}: index {'current' if current else 'STALE'}")
        return 0 if current else 1

    if args.write:
        if current:
            print(f"{args.backlog}: index already current — not rewritten")
            return 0
        args.backlog.write_text(apply_index(content, expected), encoding="utf-8")
        print(f"{args.backlog}: index written")
        return 0

    print(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
